### ISSUE TITLE
Bundle metadata is not updated

### ISSUE THREAD

**Issue by piotrpasich** [KnpLabs/KnpBundles#365]
Knpbundles.com didn't download description and readme file from github in http://knpbundles.com/xsolve-pl/xsolve-google-auth-bundle

**Comment by fracasula** [comment]
Same here: http://knpbundles.com/fracasula/PhpSandboxBundle
Am I missing something or it's just a matter of time? Does the updater run often (daily, weekly?)?

Thanks!

**Comment by Remiii** [comment]
Looks like it is not really fixed, I posted my bundle something like 3 weeks ago, still waiting for an update. Here it is : https://github.com/Remiii/remiii-mandrill-mailer-bundle

**Comment by Remiii** [comment]
@cystbear "cystbear was unassigned by Remiii a minute ago" sorry for that... I will fix it!

**Comment by wysow** [comment]
@Remiii your bundle is now updated, but please avoid putting comment in an old thread and open a new one instead.
