### ISSUE TITLE
I can change settings of strange bundles

### ISSUE THREAD

**Issue by Koc** [KnpLabs/KnpBundles#387]
http://easycaptures.com/fs/uploaded/611/2369156867.jpg

**Comment by wysow** [comment]
@Koc not easy for me to reproduce this behavior... maybe you were part of this bundle organization on github at some point?

**Comment by Koc** [comment]
I had commited something to this bundle a long time ago. But I'm not member of this organization.

**Comment by wysow** [comment]
@Koc I just take a look to the current data and you're not linked to that bundle in the system, is the bug still here?

**Comment by Koc** [comment]
Yes, http://easycaptures.com/fs/uploaded/779/5140682454.png

**Comment by wysow** [comment]
OK @Koc as you can see here https://github.com/KnpLabs/KnpBundles/blob/26c21b6135c904593b554fdb4428ad1b5eb69d40/src/Knp/Bundle/KnpBundlesBundle/Entity/Bundle.php#L1065 as soon has you contributed to the bundle you are allowed to modify it, thanks @akovalyov for letting me get this ;)

**Comment by akovalyov** [comment]
@wysow I am thinking about this issue. Maybe we should allow to modify bundle settings only to owners of the repo?  It seems to be a potential root of issues.

**Comment by wysow** [comment]
@akovalyov sure you're right will try to make it ASAP
