### ISSUE TITLE
README not displayed

### ISSUE THREAD

**Issue by Sharom** [KnpLabs/KnpBundles#404]
I registered a bundle (https://github.com/LitGroup/LitGroupEventLoopBundle) with README.md in the root of repository, but on KnpBundles displayed "No readme file found in bundle." The same with a LICENSE file.

http://knpbundles.com/LitGroup/LitGroupEventLoopBundle

**Comment by fattouchsquall** [comment]
Same bug for me: https://github.com/fattouchsquall/AMFWebServicesClientBundle,

Before also, i add a bundle and there's no Readme in knpBundles: http://knpbundles.com/fattouchsquall/AMFOpenVpnBundle

Any suggestions please?

**Comment by Remiii** [comment]
Same issue for this Bundle : https://github.com/Remiii/remiii-mandrill-mailer-bundle

Any ideas ?

**Comment by emiliano-viada-developer** [comment]
Same issue here: http://knpbundles.com/emiliano-viada-developer/HasheadoAdminBundle

Any update?

**Comment by wysow** [comment]
All bundles should now be updated very soon, closing this.

Feel free to open new issue if it's not the case for one/more of your bundles.

**Comment by kamranshahzad** [comment]
I have README.md file but not showing bundle description.
http://knpbundles.com/kamranshahzad/LayoutBundle

**Comment by ajaxray** [comment]
Not sure if this thread is still active, but posting here because it seems most relevant. 
Here is my bundle with the same issue - 
http://knpbundles.com/ajaxray/GulpBusterBundle

**Comment by mgdigital** [comment]
Same issue here: http://knpbundles.com/mgdigital/BusQueBundle

**Comment by Evgenas** [comment]
Yes, looks like the issue still exists, same for our added bundle http://knpbundles.com/smart-gamma/gamma-api-logger

**Comment by Acrack** [comment]
Hi, same here: https://github.com/Acrack/AckNotificationBundle

**Comment by lobodol** [comment]
Hi, same issue here: http://knpbundles.com/lobodol/FireDIY-PrivateMessageBundle

**Comment by ordermind** [comment]
Here too: http://knpbundles.com/ordermind/symfony-logical-authorization-bundle
