### ISSUE TITLE
Bundle metadata is not updated

### ISSUE THREAD

**Issue by pravednik** [KnpLabs/KnpBundles#427]
A similar problem with https://github.com/KnpLabs/KnpBundles/issues/365 .  Description is not updated for 2 days:  http://knpbundles.com/pravednik/xmlWrapperBundle

**Comment by wysow** [comment]
@pravednik your bundle seems as not available anymore, should we close this?

**Comment by wysow** [comment]
@pravednik seems your bundle is now known as http://www.knpbundles.com/pravednik/xmlBundle so closing this now
