### ISSUE TITLE
[RFC] add supporting PSR-0 tree structure for the bundles

### ISSUE THREAD

**Issue by TheCelavi** [KnpLabs/KnpBundles#433]
KnpBundles supports only one, unofficial, structure of bundle, witch forces developers to structure the code repository as such in order to be published on KnpBundles.

However, this constraint is sufficient, since Composer allows us to structure our bundle directory/code tree however we like.

This constraint is created to somehow validate submitted repo as a valid bundle.

However, this structure is example of valid bundle as well: https://github.com/TheCelavi/DmDecimalCalculatorBundle which can be required by Composer and included in Symfony2 project.

KnpBundles should support such use case scenarios.

**Comment by wysow** [comment]
Since this https://github.com/KnpLabs/KnpBundles/pull/438 has been merged, we can close this one.
