### ISSUE TITLE
My bundle is not properly showed on the website

### ISSUE THREAD

**Issue by bichotll** [KnpLabs/KnpBundles#434]
The information and the bundle description is not up to date.

On the other hand, I have 0 points when once I had 16.

As I'm taking a look over here: http://knpbundles.com/about/faq-scoring
I should have min more than 10. To give an idea.

http://knpbundles.com/bichotll/FormValidationBundle

Let me know if I did something wrong? Or I can do something to help you/solve it.

**Comment by wysow** [comment]
@bichotll Your bunlde content (readme, ...) should be updated soon, about the score tells us if you think it's not updated the right way...

**Comment by bichotll** [comment]
@wysow Cool! Now it works as it has to, README and score ;)

I close the issue.

Thanks,
jaume
