### ISSUE TITLE
CPTermsBundle

### ISSUE THREAD

**Issue by opichon** [KnpLabs/KnpBundles#440]
I've registered the CPTermsBundle. knpbundles says it cannot find the readme file, even though it exists.
The bundle is in the coopers-peele namespace in github, which is an organization. The bundle does not show in "my" bundles, even though I am its maintainer. It looks like I have no way of editing it.

**Comment by wysow** [comment]
@opichon Can we close this?

**Comment by opichon** [comment]
The bundle now shows under the "contributed" tab of the "My bundles" page, and I have access to its settings. So all is ok.

Many thanks.
