### ISSUE TITLE
 Bundle not updating from GitHub

### ISSUE THREAD

**Issue by Ex3v** [KnpLabs/KnpBundles#442]
Hello,

my bundle is not updating from github commits. http://knpbundles.com/Ex3v/FormErrorsBundle Is there anything I can do? Thanks.

Maciej

**Comment by javiereguiluz** [comment]
Same with my bundle :(

Could we, the Symfony community, help you, the KnpBundles site maintainers, help you in any way to solve this issue? Thanks!

**Comment by wysow** [comment]
Your bundles should be updated soon. If not feel free to open a new issue for each bundle so we can investigate.

**Comment by javiereguiluz** [comment]
@wysow thanks for fixing this issue! And thanks for creating and maintaining knpbundles.com
