### ISSUE TITLE
all my bundles are rated with 0 points. Why?

### ISSUE THREAD

**Issue by azine** [KnpLabs/KnpBundles#443]
Hi,

according to http://knpbundles.com/about/faq-scoring my bundles (search for azine) should all have scores higher than 0.

What's wrong?

Best regards,
Dominik

**Comment by azine** [comment]
Hi,

is there an update on this one?

Cheers,
d.

**Comment by wysow** [comment]
@azine your bundle should be updated soon. If not feel free to reopen this issue.

**Comment by azine** [comment]
Thanx!
