### ISSUE TITLE
Redirection page d'accueil

### ISSUE THREAD

**Issue by SebastienXD** [KnpLabs/KnpBundles#449]
Bonjour, depuis quelques jours, je me retrouve systèmatique sur la page (http://knpbundles.com/developer/best) lorsque que j'affiche la page d'accueil (http://knpbundles.com/).

Si j'arrête le chargement de la page d'accueil, la redirection ne se fait pas.

Problème visible uniquement sous Chrome.

**Comment by wysow** [comment]
@SebastienXD This should be OK now right? Closing it now...
