### ISSUE TITLE
Problème update bundle

### ISSUE THREAD

**Issue by samarhxc** [KnpLabs/KnpBundles#453]
Bonjour,
j'ai mis en ligne un bundle il y a plusieurs mois mais rien ne se met à jour sur la page (readme, contributors...).

Voici le lien : http://knpbundles.com/froala/KMSFroalaEditorBundle

Je signale que le bundle a changé de propriétaire (et donc de repo github), du coup lorsque l'on fait une recherche (http://knpbundles.com/search?q=froala), on trouve un doublon qui n'exsite plus : http://knpbundles.com/samarhxc/KMSFroalaEditorBundle

**Comment by wysow** [comment]
@samarhxc your bundle should be updated soon.

If not feel free to reopen this issue.

**Comment by samarhxc** [comment]
Hi, 
my bundle was not updated since the last time.
It's embarrasing because the documentation is out to date.
