### ISSUE TITLE
Bundle not updating from GitHub

### ISSUE THREAD

**Issue by ronisaha** [KnpLabs/KnpBundles#455]
My bundle is not updating http://knpbundles.com/xiidea/easy-audit

**Comment by wysow** [comment]
@ronisaha your bundle is now at http://knpbundles.com/xiidea/EasyAuditBundle and is up to date, the old version is not available anymore. You should update the link to knpbundles.com in your readme ;)

**Comment by ronisaha** [comment]
Thanks!

**Comment by J-Mose** [comment]
Hi, 

Mine is not updating too (readme, activity) despite some commit during last days and month.
http://knpbundles.com/J-Mose/CommandSchedulerBundle

**Comment by wysow** [comment]
@J-Mose can you make a new issue so we can track each bundle individually, thanks.
