### ISSUE TITLE
Bundle not updating

### ISSUE THREAD

**Issue by romaricdrigon** [KnpLabs/KnpBundles#460]
Hi,

I'm encountering again an issue with bundle updates: for 2 bundles added those last days, no info was fetched: 
http://knpbundles.com/netinfluence/NetinfluenceUploadBundle
http://knpbundles.com/netinfluence/SecureDisplayBundle

Is it again issues with the RabbitMQ layer?
As those are pretty common (on 4 bundles I put there, 3 had issues), maybe a "force update" button should be put or a Github hook?
Moreover, given how many issues end up here maybe displaying some debug details could help?

**Comment by wysow** [comment]
Hello @romaricdrigon it seems that this bundles are now updated right? If not can you be more precise about what is outdated?

By the way the update schedule is every 2 or 3 days as far as I can remember...

**Comment by romaricdrigon** [comment]
Yes they are!
So it's fine now. But as far as I remember, there is some text on KnpBundles saying that bundles are updated every few hours, so that's why I was wondering what was happening. Maybe that text should be modified?

**Comment by wysow** [comment]
@romaricdrigon Thanks for noticing this, will take a look at this ;)

**Comment by dextervip** [comment]
@wysow @romaricdrigon I also saw the text saying that It should be updated within few hours. I was about to open an issue until I see this. The text should be corrected to avoid issues opening But If It is updated every 2 or 3 days, I will wait it. Cheers!

**Comment by romaricdrigon** [comment]
I'm posting again here, in 2 weeks the bundle have not been updated at all: http://knpbundles.com/netinfluence/NetinfluenceUploadBundle

Is everything good?

**Comment by wysow** [comment]
@romaricdrigon Seems your bundle has not been updated since 13 days, as visible on the last commit page https://github.com/netinfluence/NetinfluenceUploadBundle/commit/c1ad1c54e29e9be59457f0db04726afbd2b7c4e7 

So for me everything is fine...

**Comment by romaricdrigon** [comment]
The KnpBundles page is way older than that: last update is from 04-24, you can see the README is really different.

**Comment by wysow** [comment]
@romaricdrigon OK will take a look, as far as I can remember all bundles are not always updated...
