### ISSUE TITLE
Dead project ?

### ISSUE THREAD

**Issue by GromNaN** [KnpLabs/KnpBundles#487]
Hi, there isn't any bundle listed on [knpbundles.com](http://knpbundles.com/) the "latest activities" are 7 years old (https://github.com/KnpLabs/KnpBundles/issues/474). 

Symfony Bundles are listed on Packagist : https://packagist.org/?type=symfony-bundle

This project could be reworked to list bundle using packagist API or, easier, redirect to it.

**Comment by alexpozzi** [comment]
We are finalizing a new version of the website (we rewrote it from scratch) and it will soon be available.

**Comment by GromNaN** [comment]
Cool 👍🏻. Nothing is happening on this open repository. Perhaps you are working in the secret of a private project.

I didn't see this red message at first on the site. And didn't know if was still relevant.
![image](https://user-images.githubusercontent.com/400034/174284410-22c11356-82a9-4398-8353-74c7c90364a3.png)
